apiVersion: v1
kind: Pod
metadata:
  labels:
    app: webapp
  name: webapp1
spec:
  containers:
  - name: webapp
    image: nginx
    resources:
      requests:
        memory: 50Mi
        cpu: 50m
      limits:
        memory: 100Mi
        cpu: 50m
